B task2097 txemi acceder hostscripts
isetic/nmap4j pull request #1
Opened 2018-02-04 21:42 UTC by txemi

Implements accessing to hostscripts data in nmap result.

Unit test added.

2018-02-15 12:26 UTC, jonmi requested changes

2018-02-15 12:26 UTC, jonmi commented on src/main/java/org/nmap4j/data/host/ports/Port.java
> +	private LinkedList<Script> scripts = new LinkedList<>();
Sería mejor usar un mapa? sobre todo para cuando necesites obtener un Script a partir de su id.

2018-02-15 12:26 UTC, jonmi commented on src/main/java/org/nmap4j/data/host/scripts/HostScript.java
> +    private LinkedList<Script> scripts = new LinkedList<>();
La misma recomendación que la anterior.

2018-02-15 12:26 UTC, jonmi commented on src/main/java/org/nmap4j/parser/NMapRunHandlerImpl.java
>  	public Hostnames createHostnames(Attributes attributes) {
Para que se pasan unos atributos si luego no se utilizan?

2018-02-15 12:26 UTC, jonmi commented on src/main/java/org/nmap4j/parser/NMapRunHandlerImpl.java
> +	private void noop() {
Elimina esta funcion

2018-02-15 12:26 UTC, jonmi commented on src/main/java/org/nmap4j/parser/NMapRunHandlerImpl.java
> +		if (portValue != null)
Puede llegar a ser el valor vacio?

2018-02-15 12:26 UTC, jonmi commented on src/main/java/org/nmap4j/parser/NMapRunHandlerImpl.java
> +		if (protValue != null)
Lo mismo que el anterior.

2018-02-15 12:26 UTC, jonmi commented on src/main/java/org/nmap4j/parser/NMapRunHandlerImpl.java
> +			logger.info( "Bad rtt for hop --" );
Tiene sentido crear un Hop cuando no tiene rtt?

2018-02-15 12:26 UTC, jonmi commented on src/main/java/org/nmap4j/parser/NMapRunHandlerImpl.java
> +		Script script = new Script();
No compendo muy bien esta funcion, estas declarando variables que luego no usas, y no tengo claro de si puedes llegar a machacar los ids y outputs de la clase script.

2018-02-15 12:26 UTC, jonmi commented on src/main/java/org/nmap4j/parser/NMapXmlHandler.java
> +	private void noop() {
Elimina esta funcion.

2018-02-15 12:26 UTC, jonmi commented on src/main/java/org/nmap4j/parser/NMapXmlHandler.java
> +		if (processHostScripts) {
Se tiene pensado que esta variable sea siempre true? o que su valor sea en función de un fichero de propiedades o algo? Si va a ser siempre true, eliminar esta variable y su if.

2018-02-15 12:26 UTC, jonmi commented on src/main/java/org/nmap4j/parser/NMapXmlHandler.java
> +					throw new RuntimeException();
Da algo mas de información en las excepciones, estaría bien un texto explicando que es lo que esta mal o que es lo que falta.

2018-02-15 12:26 UTC, jonmi commented on src/main/java/org/nmap4j/parser/NMapXmlHandler.java
> +				if (false && this.script == null) {
Que funcionalidad tiene esto?

2018-02-15 12:26 UTC, jonmi commented on src/main/java/org/nmap4j/parser/NMapXmlHandler.java
> +		if (elemkey != null) {
Añadir a esta condición que el script sea distinto a nulo, así the evitas el crear una nueva variable.

2018-02-15 12:26 UTC, jonmi commented on src/main/java/org/nmap4j/parser/NMapXmlHandler.java
> +				} else if (this.port != null) {
Que diferencia hay cuando el hostscript no es nulo o el puerto no es nulo? a mi parecer es el mismo codigo, porque ponerlo todo en una unica condición?

2018-02-15 12:26 UTC, jonmi commented on src/test/java/org/nmap4j/parsers/OnePassParserTest.java
> +            System.out.println("");
Que es lo que pretendes sacar por la salida?, veo que los print no sacan nada, y no hay mas en todo el test.

2018-02-15 12:26 UTC, jonmi commented on src/test/java/org/nmap4j/parsers/OnePassParserTest.java
> +    public void testHostScript2() {
Que tiene este metodo? Veo que el poco codigo que tiene es el mismo que el anterior, ademas veo que esta ignorado. Si no va a probar nada y ademas no contiene nada nuevo es mejor eliminarlo.

2018-02-15 12:26 UTC, jonmi commented on src/test/java/org/nmap4j/parsers/OnePassParserTest.java
> +    public void testHostScript() {
No entiendo muy bien lo que comprueba ese test.
Se lee un fichero y va mirando si hay elementos cargados, si los hay, mira si el SO es Windows 7 y en ese caso peta.
No veo mucho sentido en este test.

2018-02-15 12:27 UTC, jonmi requested changes
Corrige varias cosas.

2018-02-16 10:29 UTC, txemi commented on src/main/java/org/nmap4j/data/host/ports/Port.java
> +	private LinkedList<Script> scripts = new LinkedList<>();
Es una lista enana si la hay y no quería andar pensando qué pasa si no hay id. 
Si no hay id y nadie consulta por Id evito buscar problemas.
El rendimiento en una lista de tres elementos o ninguno no me ha preocupado.

2018-02-16 10:29 UTC, txemi commented on src/main/java/org/nmap4j/data/host/scripts/HostScript.java
> +    private LinkedList<Script> scripts = new LinkedList<>();
idem

2018-02-16 10:32 UTC, txemi commented on src/main/java/org/nmap4j/parser/NMapRunHandlerImpl.java
>  	public Hostnames createHostnames(Attributes attributes) {
Esa parte yo no la he tocado, estaba así en mainstream. No sé si es intencionado por alguna simetría o un descuido.
He preferido tocar lo menos posible.

2018-02-16 10:33 UTC, txemi commented on src/main/java/org/nmap4j/parser/NMapRunHandlerImpl.java
> +	private void noop() {
eliminado

2018-02-16 10:34 UTC, txemi commented on src/main/java/org/nmap4j/parser/NMapRunHandlerImpl.java
> +		if (portValue != null)
creo que esto estaba así.

2018-02-16 10:37 UTC, txemi commented on src/main/java/org/nmap4j/parser/NMapXmlHandler.java
> +		if (elemkey != null) {
reorganizado, el resultado es el mismo y queda mejor así.

2018-02-16 10:38 UTC, txemi commented on src/main/java/org/nmap4j/parser/NMapXmlHandler.java
> +				} else if (this.port != null) {
ok, lo cambio.

2018-02-16 10:40 UTC, txemi commented on src/test/java/org/nmap4j/parsers/OnePassParserTest.java
> +            System.out.println("");
ok

2018-02-16 11:15 UTC, txemi commented on src/test/java/org/nmap4j/parsers/OnePassParserTest.java
> +    public void testHostScript2() {
ok, quería probar ficheros de nmap nuevos pero no me atreví a subirlos porque deberían ser suficientemente anónimos. Lo borro como dices.

2018-02-16 11:16 UTC, txemi commented on src/test/java/org/nmap4j/parsers/OnePassParserTest.java
> +    public void testHostScript() {
Al revés, la condición está negada. Si no es el valor esperado peta.

2018-02-16 15:36 UTC, txemi commented on src/main/java/org/nmap4j/parser/NMapRunHandlerImpl.java
> +		if (portValue != null)
Añado el comentario que pedías.

2018-02-16 15:51 UTC, txemi commented on src/main/java/org/nmap4j/parser/NMapRunHandlerImpl.java
> +			logger.info( "Bad rtt for hop --" );
No lo sé, pero lo que no quiero es escribir código que pierda información. He metido esa condición porque se ha dado y sino peta. Los otros valores pueden tener información. Para lo que yo necesito de esta librería me puede interesa tener información antes que no tenerla.

2018-02-16 16:21 UTC, txemi reviewed
Jonmi, ya he hecho los cambios.

2018-02-16 16:21 UTC, txemi commented on src/main/java/org/nmap4j/parser/NMapRunHandlerImpl.java
> +		Script script = new Script();
Borro el código no usado.
He implementado los atributos que necesito para nosotros y funciona. Si algún día necesito más los añadiré.
Ha sido probado en bastantes escaneos de nmap y no ha petado.
Sobre si en un XML pudiese haber atributos repetidos eso es competencia de la librería sax y debería testarse allí. Si fuese código mío igual metía en eso pero ahora si meto más código aquí no consigo beneficios para nuestra parte. En todo caso igual petan cosas que antes no petaban.

2018-02-16 16:21 UTC, txemi commented on src/main/java/org/nmap4j/parser/NMapXmlHandler.java
> +	private void noop() {
eliminada

2018-02-16 16:21 UTC, txemi commented on src/main/java/org/nmap4j/parser/NMapXmlHandler.java
> +		if (processHostScripts) {
Lo quito.

2018-02-16 16:21 UTC, txemi commented on src/main/java/org/nmap4j/parser/NMapXmlHandler.java
> +					throw new RuntimeException();
Hecho

2018-02-16 16:21 UTC, txemi commented on src/main/java/org/nmap4j/parser/NMapXmlHandler.java
> +				if (false && this.script == null) {
Algo que me pareció raro y no llegué a entender, lo cambio por un comentario para que quede constancia y en la posteridad si alguien piensa sobre ello y ve el comentario podamos hablar.

2018-02-18 15:55 UTC, jonmi approved these changes

2018-02-19 09:24 UTC, jonmi approved these changes

2018-02-19 09:25 UTC, jonmi approved these changes

2018-02-19 09:29 UTC, merged