task2209 txemi arreglar relacion osmatch osclass
isetic/nmap4j pull request #2
Opened 2018-02-23 22:29 UTC by txemi

Nueva versión de nmap4j para no perder la relación entre osmatch y osclass

2018-02-27 15:19 UTC, jonmi requested changes

2018-02-27 15:19 UTC, jonmi commented on src/main/java/org/nmap4j/parser/NMapXmlHandler.java
> +				throw new RuntimeException(  );
Put some message explaining all the exceptions

2018-02-27 15:19 UTC, jonmi commented on src/main/java/org/nmap4j/parser/NMapXmlHandler.java
> +				if("postscript".equals( previousQName) ){
Empty if.

2018-02-27 15:19 UTC, jonmi commented on src/test/java/org/nmap4j/parsers/NMapXmlHandlerTest.java
> +		InputStream in = getClass().getClassLoader().getResourceAsStream( NmapDataSamples.fileName );
Are you closing the InputStream?

2018-02-27 15:19 UTC, jonmi commented on src/test/java/org/nmap4j/parsers/OnePassParserTest.java
>  import org.nmap4j.data.host.scripts.HostScript;
Close all the InputStream, that is a big mistake.

2018-02-28 12:22 UTC, txemi commented on src/main/java/org/nmap4j/parser/NMapXmlHandler.java
> +				throw new RuntimeException(  );
Done

2018-02-28 12:23 UTC, txemi commented on src/main/java/org/nmap4j/parser/NMapXmlHandler.java
> +				if("postscript".equals( previousQName) ){
Explained with TODO.

2018-02-28 12:23 UTC, txemi commented on src/test/java/org/nmap4j/parsers/NMapXmlHandlerTest.java
> +		InputStream in = getClass().getClassLoader().getResourceAsStream( NmapDataSamples.fileName );
Done.

2018-02-28 12:23 UTC, txemi commented on src/test/java/org/nmap4j/parsers/OnePassParserTest.java
>  import org.nmap4j.data.host.scripts.HostScript;
Done.

2018-02-28 14:36 UTC, jonmi requested changes

2018-02-28 14:36 UTC, jonmi commented on src/main/java/org/nmap4j/parser/NMapXmlHandler.java
> +				throw new InternalError( nestedTagErrorMsg(qName) );
Why do you think that InternalError is the best exception instead of RuntimeException?
According to the class his use is for "Thrown to indicate some unexpected internal error has occurred in the Java Virtual Machine."
I don't think that is the case of that

2018-02-28 14:36 UTC, jonmi commented on src/main/java/org/nmap4j/parser/NMapXmlHandler.java
>  			} else if (previousQName.equals(Service.SERVICE_TAG)) {
Else if empty.

2018-02-28 14:36 UTC, jonmi commented on src/main/java/org/nmap4j/parser/NMapXmlHandler.java
> +				if("postscript".equals( previousQName) ){
Are you going to implement it? in the case that in short term that is not going to happen, I prefer to put out the comment and delete the If condition.

2018-02-28 14:36 UTC, jonmi commented on src/test/java/org/nmap4j/parsers/OnePassParserTest.java
>  import org.nmap4j.data.host.scripts.HostScript;
Not, they are not. They still being several InputStream that are not closing.

2018-02-28 14:55 UTC, txemi commented on src/main/java/org/nmap4j/parser/NMapXmlHandler.java
> +				if("postscript".equals( previousQName) ){
No borro la condición porque no es la misma lógica, en un caso se lanza una excepción y en otra no.

2018-02-28 15:08 UTC, txemi commented on src/main/java/org/nmap4j/parser/NMapXmlHandler.java
> +				throw new InternalError( nestedTagErrorMsg(qName) );
Cambiado

2018-02-28 15:11 UTC, txemi commented on src/test/java/org/nmap4j/parsers/OnePassParserTest.java
>  import org.nmap4j.data.host.scripts.HostScript;
Alguno que haya añadido yo a la librería? Cual?

2018-02-28 15:13 UTC, txemi commented on src/main/java/org/nmap4j/parser/NMapXmlHandler.java
>  			} else if (previousQName.equals(Service.SERVICE_TAG)) {
No lo entiendo. ¿Qué problema hay?

2018-02-28 15:39 UTC, jonmi commented on src/main/java/org/nmap4j/parser/NMapXmlHandler.java
> +				if("postscript".equals( previousQName) ){
Pues que no debe de haber un codigo el que se este mirando una condición para no hacer nada, y que se lance una excepción en caso contrario.

En vez de eso pones un if (caso excepcion){lanzo excepcion} y dejas un comentario en caso contrario.

No hay que poner ni ifs ni funciones que no hagan nada, porque es sucio.

2018-02-28 15:45 UTC, jonmi commented on src/main/java/org/nmap4j/parser/NMapXmlHandler.java
>  			} else if (previousQName.equals(Service.SERVICE_TAG)) {
Que este else if:
} else if (previousQName.equals(Service.SERVICE_TAG)) {

			}
esta vacio.

2018-02-28 15:49 UTC, jonmi commented on src/main/java/org/nmap4j/parser/NMapXmlHandler.java
> +				throw new RuntimeException(  );
No es mejor que si el problema es al formatear un fichero XML se lance un SAXException o un XMLParseException en vez de un RuntimeException que no aporta nada y los otros explican un poco mas el porque de la excepcion?

2018-02-28 16:08 UTC, txemi commented on src/main/java/org/nmap4j/parser/NMapXmlHandler.java
>  			} else if (previousQName.equals(Service.SERVICE_TAG)) {
Dejo un comentario de por qué.

2018-02-28 16:08 UTC, txemi commented on src/main/java/org/nmap4j/parser/NMapXmlHandler.java
> +				if("postscript".equals( previousQName) ){
Supongo que "sucio" es subjetivo, porque a mí me parece claro si las condiciones válidas van primero y todo lo no contemplado o erróneo (excepción) al final. Además si alguien quiere implementarlo porque lo necesita tiene el TODO donde rellenar el código, y si en el futuro aparecen casos nuevos se añadirían nuevos "else if" Desde mi punto de vista la estructura "limpia" es esta.
Para el compilador lo que planteas tampoco es mejor porque es suficientemente listo.
Lo que quiero castigar con una excepción es el no encontrar caso correcto, ponerlo como dices da a entender que sólo hay un caso válido. Esta forma comunica mejor lo que se pretende.

2018-03-01 13:41 UTC, jonmi approved these changes

2018-03-02 20:48 UTC, merged